import React from 'react';
import { motion } from 'framer-motion';

const TermsPage = () => {
  return (
    <>
      <section className="page-hero">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <span className="section-tag">📋 Legal</span>
          <h1 className="section-title">Terms of Service</h1>
          <p className="section-subtitle">
            Last updated: March 7, 2026
          </p>
        </motion.div>
      </section>

      <section className="legal-content">
        <div className="legal-inner">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the Dressly application and website
            (collectively, the "Service"), you agree to be bound by these Terms
            of Service. If you do not agree to these terms, do not use the
            Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            Dressly is an AI-powered fashion advisory platform that allows
            users to upload clothing images, receive AI-generated outfit
            suggestions, and manage their digital wardrobe. The Service is
            available as a mobile application (iOS and Android) and a web
            application.
          </p>

          <h2>3. User Accounts</h2>
          <p>
            To use certain features of the Service, you must create an account.
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activities that occur under your
            account.
          </p>
          <ul>
            <li>You must provide accurate and complete information</li>
            <li>You must be at least 13 years old to create an account</li>
            <li>You are responsible for all activity under your account</li>
            <li>You must notify us immediately of any unauthorized use</li>
          </ul>

          <h2>4. Subscription Plans</h2>
          <h3>Free Tier</h3>
          <p>
            The free tier provides limited access to AI outfit generation (5
            per day), basic wardrobe management, and community support.
          </p>
          <h3>Pro Tier</h3>
          <p>
            The Pro subscription provides unlimited AI generations, advanced
            AI models, full wardrobe features, and priority support. Pricing
            is set dynamically by our administration and may change with
            notice.
          </p>
          <h3>Billing</h3>
          <p>
            Pro subscriptions are billed monthly through Razorpay. You may
            cancel your subscription at any time. Cancellation takes effect at
            the end of the current billing period.
          </p>

          <h2>5. User Content</h2>
          <p>
            You retain ownership of all images and content you upload to the
            Service. By uploading content, you grant Dressly a limited license
            to process, store, and display your content for the purpose of
            providing the Service.
          </p>
          <ul>
            <li>You must own or have rights to the content you upload</li>
            <li>You must not upload illegal, harmful, or inappropriate content</li>
            <li>We may remove content that violates these terms</li>
          </ul>

          <h2>6. AI-Generated Content</h2>
          <p>
            Outfit suggestions generated by our AI are provided "as is" for
            informational and entertainment purposes. Dressly does not guarantee
            the accuracy, completeness, or suitability of AI recommendations.
          </p>

          <h2>7. Prohibited Uses</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any illegal purpose</li>
            <li>Attempt to reverse-engineer or hack the Service</li>
            <li>Abuse the API or exceed rate limits</li>
            <li>Create multiple accounts to circumvent free tier limits</li>
            <li>Upload content that infringes on intellectual property rights</li>
            <li>Use automated tools to scrape or collect data from the Service</li>
          </ul>

          <h2>8. Intellectual Property</h2>
          <p>
            The Dressly name, logo, software, and all associated intellectual
            property are owned by Dressly Inc. The source code is available
            under an open-source license on GitHub.
          </p>

          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Dressly shall not be liable
            for any indirect, incidental, special, consequential, or punitive
            damages arising out of or relating to your use of the Service.
          </p>

          <h2>10. Termination</h2>
          <p>
            We may suspend or terminate your account at any time for violation
            of these terms. You may delete your account at any time through the
            app settings.
          </p>

          <h2>11. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will
            notify users of material changes via email or in-app notification.
            Continued use of the Service after changes constitutes acceptance.
          </p>

          <h2>12. Contact</h2>
          <p>
            For questions about these Terms, contact us at{' '}
            <a href="mailto:legal@dressly.app" style={{ color: 'var(--primary-light)' }}>
              legal@dressly.app
            </a>.
          </p>
        </div>
      </section>
    </>
  );
};

export default TermsPage;
